# INSERT INTO cars (make, model, price, year_of_registration, mileage, color, body_type, fuel_type) VALUES ('Toyota', 'Corolla', 25000, 2022, 10000, 'Blue', 'SEDAN', 'GASOLINE');
# INSERT INTO cars (make, model, price, year_of_registration, mileage, color, body_type, fuel_type) VALUES ('Honda', 'Civic', 20000, 2021, 15000, 'Red', 'COMPACT', 'DIESEL');
# INSERT INTO cars (make, model, price, year_of_registration, mileage, color, body_type, fuel_type) VALUES ('BMW', 'Z4', 40000, 2020, 8000, 'Black', 'CONVERTIBLE', 'GASOLINE');
# INSERT INTO cars (make, model, price, year_of_registration, mileage, color, body_type, fuel_type) VALUES ('Toyota', 'Prius', 30000, 2019, 30000, 'Silver', 'WAGON', 'HYBRID');
# INSERT INTO cars (make, model, price, year_of_registration, mileage, color, body_type, fuel_type) VALUES ('Tesla', 'Model S', 80000, 2022, 5000, 'White', 'COUPE', 'ELECTRIC');
# INSERT INTO cars (make, model, price, year_of_registration, mileage, color, body_type, fuel_type) VALUES ('Audi', 'Q5', 45000, 2021, 20000, 'Gray', 'SUV', 'DIESEL');
# INSERT INTO cars (make, model, price, year_of_registration, mileage, color, body_type, fuel_type) VALUES ('Ford', 'Focus', 22000, 2020, 18000, 'Green', 'HATCHBACK', 'GASOLINE');
# INSERT INTO cars (make, model, price, year_of_registration, mileage, color, body_type, fuel_type) VALUES ('Volkswagen', 'Passat', 35000, 2018, 25000, 'Black', 'SEDAN', 'CNG');
# INSERT INTO cars (make, model, price, year_of_registration, mileage, color, body_type, fuel_type) VALUES ('Mercedes-Benz', 'Sprinter', 55000, 2019, 40000, 'White', 'VAN', 'OTHER');
# INSERT INTO cars (make, model, price, year_of_registration, mileage, color, body_type, fuel_type) VALUES ('Ford', 'Transit', 40000, 2020, 30000, 'Blue', 'TRANSPORTER', 'GASOLINE');
# INSERT INTO cars (make, model, price, year_of_registration, mileage, color, body_type, fuel_type) VALUES ('Chevrolet', 'Impala', 28000, 2019, 35000, 'Silver', 'OTHER', 'ETHANOL');
# INSERT INTO cars (make, model, price, year_of_registration, mileage, color, body_type, fuel_type) VALUES ('Fiat', 'Doblo', 20000, 2018, 40000, 'Yellow', 'OTHER', 'LPG');
# INSERT INTO cars (make, model, price, year_of_registration, mileage, color, body_type, fuel_type) VALUES ('Toyota', 'Rav4', 35000, 2020, 25000, 'Black', 'SUV', 'HYBRID');
# INSERT INTO cars (make, model, price, year_of_registration, mileage, color, body_type, fuel_type) VALUES ('Hyundai', 'Kona', 30000, 2021, 15000, 'Red', 'OTHER', 'HYBRID');
# INSERT INTO cars (make, model, price, year_of_registration, mileage, color, body_type, fuel_type) VALUES ('Nissan', 'Leaf', 32000, 2019, 20000, 'Blue', 'ELECTRIC', 'GASOLINE');
# INSERT INTO cars (make, model, price, year_of_registration, mileage, color, body_type, fuel_type) VALUES ('Volvo', 'XC60', 45000, 2020, 18000, 'Gray', 'SUV', 'DIESEL');
# INSERT INTO cars (make, model, price, year_of_registration, mileage, color, body_type, fuel_type) VALUES ('Lexus', 'RC', 60000, 2022, 5000, 'Black', 'COUPE', 'OTHER');
# INSERT INTO cars (make, model, price, year_of_registration, mileage, color, body_type, fuel_type) VALUES ('Kia', 'Niro', 33000, 2020, 15000, 'Green', 'SUV', 'HYBRID');
# INSERT INTO cars (make, model, price, year_of_registration, mileage, color, body_type, fuel_type) VALUES ('Subaru', 'Outback', 40000, 2019, 20000, 'Brown', 'OTHER', 'CNG');
# INSERT INTO pictures(filename, priority, car_id) VALUES ('picture1.jpg',true,1);
# INSERT INTO pictures(filename, priority, car_id) VALUES ('picture2.jpg',false,1);
# INSERT INTO pictures(filename, priority, car_id) VALUES ('picture3.jpg',false,1);
# INSERT INTO pictures(filename, priority, car_id) VALUES ('picture4.jpg',false,2);
# INSERT INTO pictures(filename, priority, car_id) VALUES ('picture5.jpg',false,2);
# INSERT INTO pictures(filename, priority, car_id) VALUES ('picture6.jpg',true,2);
# INSERT INTO users(id,email, password, username) VALUES (1,'admin@gmail.com','$2a$10$oaE/F6/IIU/MyyBof6pzj.3Zgd.gTWMVEivJ.tNnmlQo.Yk/rjnMe','admin');
# INSERT INTO user_roles(user_id, roles) VALUES (1,'ROLE_ADMIN');
# INSERT INTO users(id,email, password, username) VALUES (2,'user@gmail.com','$2a$10$7l39OqpUHOvA8l4srVhjx.pOe6Dq4mqZQrWWgFT2k1L9ygvH7anHG','user');
# INSERT INTO user_roles(user_id, roles) VALUES (2,'ROLE_USER');